### ISSUE TITLE
captcha broken on account recovery page

### ISSUE THREAD

**Issue by jdbrice** [gzuidhof/starboard-notebook#108]
<img width="636" alt="Screen Shot 2022-04-15 at 12 04 26 " src="https://user-images.githubusercontent.com/6765220/163596080-12fff234-e255-48da-bf44-3b3f78596634.png">

Tried recovery on firefox, safari, chrome on desktop and mobile.
I get the same error on all of them.

thanks for starboard!

**Comment by gzuidhof** [comment]
Ah, this is an issue on the backend 🤦, I'll have to redeploy to merge this change (haven't done that in quite a while).

**Comment by Waschi97** [comment]
Still bugged.

**Comment by gzuidhof** [comment]
This has been solved now.
