### ISSUE TITLE
Erratic behaviour on "Change Cell Type" button

### ISSUE THREAD

**Issue by llagerlof** [gzuidhof/starboard-notebook#11]
If the user click on "Change Cell Type" button, and after that click on "Cancel" button, the "Change Cell Type" button doesn't work anymore.

**Comment by gzuidhof** [comment]
The behaviour of those buttons is ill-implemented right now, I'll try to fix it in an upcoming release.

For now a workaround if you click on the close button: click anywhere else on the page and it will work again.

Thank you for letting me know

**Comment by gzuidhof** [comment]
Fixed in 0.4.3 :)
