### ISSUE TITLE
litHtml

### ISSUE THREAD

**Issue by riziles** [gzuidhof/starboard-notebook#115]
The currency converter in the [Data Visualization in JS](https://starboard.gg/#visualization) demo doesn't work unless I add

`const litHtml = await import('https://cdn.skypack.dev/lit-html');`

in one of the code cells.

**Comment by gzuidhof** [comment]
Thank you for letting me know, the breaking change was renaming `litHtml` to `lit`. I'll update the example notebook.

**Comment by riziles** [comment]
> Thank you for letting me know, the breaking change was renaming `litHtml` to `lit`. I'll update the example notebook.

My pleasure... By the way this product is super cool. I can't wait until you add AssemblyScript cells! That will be the coolest...
