### ISSUE TITLE
Error in Markdown cells when Shift+Enter is used

### ISSUE THREAD

**Issue by pyRobShrk** [gzuidhof/starboard-notebook#16]
I am accustomed to the Jupyter Shift+Enter shortcut, which I'm very glad is supported in Starboard. When editing Markdown cells, it seems this shortcut does render the MD, but it doesn't "stop editing". If you go to edit another cell after nothing shows up - it will still be typing it in the already-rendered md cell being previously edited. I also typically edit MD cells by double clicking. From some crude testing I think it's only an issue if all of these conditions are met:

- Firefox browser (83.0 64-bit on Windows)
- Shift+Enter shortcut used to run Markdown Cell
- Advanced Editor being used

When it happens it seems there's no way to stop editing the cell, even if you delete the glitch cell. I end up saving and re-loading the whole notebook.

**Comment by gzuidhof** [comment]
Thank you for letting me know, I wasn't able to exactly reproduce it in Firefox on a Macbook, but saw different broken behavior: Shift enter in a markdown cell renders it, and then if you try to edit again you can't make any changes. I'll have a look at fixing this.

Currently whenever you switch between render / edit mode it creates and deletes the editor again. A cell has a "top" and a "bottom", markdown always renders in the top (editor or rendered).

Moving into the future I think instead what should be supported is a **way to hide the top or bottom of a cell**, like the current "collapse cell". This will also be really useful for HTML cells and other cells you only want to show the output of without code. Then we don't have to delete and re-create the editor every time too which will probably fix this bug :)

**Comment by pyRobShrk** [comment]
I think that's the same error, but for me I can't make any further changes to that markdown cell, or any others cells (code or markdown). And if I save the notebook and re-load, everything I was _trying_ to type into all the other cells shows up in the original markdown cell that caused the glitch. The kind of weird thing is that the error doesn't happen if you use the "play button" to render the cell, only with Shift+Enter.

**Comment by gzuidhof** [comment]
This is a pretty old issue by now, but with the new WYSIWYG editor this is no longer an issue :).

Next step is also solving it in the code/plaintext editors..

**Comment by gzuidhof** [comment]
Solved, finally :)
