### ISSUE TITLE
Update to pyodide 0.16?

### ISSUE THREAD

**Issue by unhott** [gzuidhof/starboard-notebook#17]
Only just found this but I love it. I believe pyodide released 0.16 and was wondering if there's a way to incorporate this instead of 0.15 into a notebook.

**Comment by gzuidhof** [comment]
Good call, thanks for letting me know it released, I updated it to use Pyodide 0.16.1. This it was now also possible to have Sympy output rendered with KaTeX automatically :). I pushed version 0.7.8 with this change.

![https://i.imgur.com/VwfAYyl.png](https://i.imgur.com/VwfAYyl.png)
