### ISSUE TITLE
Configuring from another site? 

### ISSUE THREAD

**Issue by unhott** [gzuidhof/starboard-notebook#18]
Is it possible to configure the notebook so that, for example, you disallow js cells, or default new cells to python?

**Comment by gzuidhof** [comment]
Yes and no: there is no clean way to do so currently - but given that you can script the notebook in any way you like you can still hack it in:
```
runtime.definitions.cellTypes.map.delete("js")
runtime.definitions.cellTypes.map.delete("javascript")
```

You would run this in the window containing the notebook. Any invoking from "another site" would have to be built by you. Note that even if you disallow JS cells, the user can still open their browser console and execute code there instead.

**Default cell type**
Right now the cell type defaults to the cell type next to which you pressed the `New Cell` button. If no cell is present it does default to JS with no way to change it. I can expose a setting to change this on the runtime if that would help your usecase.

**Comment by unhott** [comment]
Awesome, thanks for the info! 

I was taking a closer look at the examples and the current functionality. It seems as though I could 'imply' a default of python by initializing a notebook with a python cell and new cells added will also be python, so I don't think a exposing a setting will by necessary at this time. 
I need to tinker around with this some more. 

Perhaps this config option is a bit more involved than the previous examples I mentioned, but what about the ability to lock a notebook and specify which cells a user can edit?  What I have in mind is something like posting a challenge that a user has to solve, but provide some starter code and tests to run at the end, but the user can only edit specific cells in the middle.

**Comment by unhott** [comment]
So I have studied this project a bit and thought about this some more. 

I am thinking it would be nice to have a 'locked' cell property that allows the code to be run but, when locked, the user can't edit the cell contents. 

I don't know ts to be able to really understand how this project works or how to contribute right now, but I'm willing to give it a shot if you can help point me in the places I need to go. With my limited understanding of what is going on, it looks like I would need to 

Add to src/cellProperties/registry.ts  -- builtinCellProperties, something to represent locked. 
And figure out where to add the function that sets the cell contents as locked-- I'm feeling pretty lost on this part, and I suspect if I were to find it I would still be unsure as to what it would do. 

It probably isn't that simple but that's where I'm currently at on this. 

And later a way of locking the notebook from allowing Cell creation, deletion, and property modification. These should get me extremely close to my end goal.

**Comment by unhott** [comment]
After spending a great deal of time trying to figure out how typescript generally works and how each of these projects work, and with the help of the cm discussion board I was able to add a cell lock toggle and get both monaco / codemirror editors to lock on creation, but I can't figure out how or where to add the ability for the editors to lock when the setting is toggled. 

ketch on the cm discussion forum was extremely helpful, and gave a starting point for how to update the read only state of the editor after creation, but I don't know exactly how to fit it into this one. 
https://discuss.codemirror.net/t/is-there-a-way-to-set-editor-to-readonly-when-you-can-only-access-the-editorview-editorstate-and-an-instance-of-editorview-in-the-new-cm/2832/2 

I was thinking maybe I needed to add some method to each editorInstance and invoke it when the contendChanged is fired, but I don't really know how to do that or if that is the best method. 

Please let me know if you are able to take a look at what I have so far and if you have any ideas that would complete this functionality :)

**Comment by gzuidhof** [comment]
Hi unhott,

I'm sorry for the very late reply - I wanted to write up a proper response and it kind of fell through. Thank you for taking the time to contribute and even learn new tools for it!
If it helps we can maybe open a text chat somewhere and I can answer smaller questions more quickly and you can get faster feedback (not sure about what would be a good platform for that nowadays though, Slack?). The downside is that any discussions there won't be searchable/findable through Google..

---

### Locked cells

A `locked` cell property makes sense. There is currently no feedback loop into the editors, and the class that manages the creation of the text editors needs a rework (it could be half the lines of code with way less hacks). I'm talking about [this file](https://github.com/gzuidhof/starboard-notebook/blob/master/src/components/textEditor.ts).

One way we can currently implement this is by registering a callback to [`cellContentChanges`](https://github.com/gzuidhof/starboard-notebook/blob/0bd5f25f8a696530c609ed0b91b6e5d063975265/src/runtime/index.ts#L177-L181), it allows you to ask for a function to be called whenever the cell's text representation changes. As the cell's text representations includes any properties, it should trigger. 

You can access it through [`runtime.subscribeToCellChanges`](https://github.com/gzuidhof/starboard-notebook/blob/0bd5f25f8a696530c609ed0b91b6e5d063975265/src/runtime/index.ts#L58-L63).

Some pseudocode:

```typescript
export function createMonacoEditor(element: HTMLElement, cell: Cell, opts: {language?: MonacoEditorSupportedLanguage; wordWrap?: WordWrapSetting}, runtime: Runtime) {
  const editor = monaco.editor.create(element, { ... });
  
  let isLocked = undefined;
  // Note it probably makes sense to make this a separate function so we can also call it right now.
  runtime.subscribeToCellChanges(cell.id, () => {
     // Note this function will be called on ALL text changes, so any letter typed,
     // it's probably better for performance to only ask Monaco to change it's editable state if it actually changed.
     if (isLocked === cell.metadata.properties.locked) return;
     isLocked = cell.metadata.properties.locked;
    
     editor.setEditable(!isLocked);
  });

  ....
}
```

I think this is the easiest way to implement it as it stands :)

---
### Notebook-wide settings (e.g. cell creation lock)

Right now Starboard notebook has no notebook-wide metadata that is persisted, but there is a place for that :). Notebooks start with a YAML header, you can access this in `runtime. See [this definition](https://github.com/gzuidhof/starboard-notebook/blob/0bd5f25f8a696530c609ed0b91b6e5d063975265/src/types.ts#L44-L62). You can access this in your code through `runtime.content.metadata` if I recall correctly. Note how there's a default cell type there - but I don't think it's actually used, to do!

Here we could add something that indicates that certain parts of the notebook are locked, frozen, uneditable, or some other naming. I'm not sure what it should be called, and whether it should actually be part of the notebook text definition.

**Right now I'm leaning towards not writing this to the notebook file** but instead allowing this to be toggled from the parent of the iframe or through code (more like the title of this issue!). Perhaps it makes sense if there is some sort of "RuntimeConfig" which is just a JSON object that toggles certain behaviors and settings (e.g. default cell language, not loading certain cell types on init, editor preference, dark mode, etc).

Then in the notebook itself we can just have a simple `if` statement to disable cell creation etc, and perhaps not show the button either. In general perhaps also notebooks need some sort of 'toast' system for user feedback, and also some UI to edit this notebook-wide metadata manually.. Lots of improvements to be made - but let's take it one step at a time!

**Comment by unhott** [comment]
No problem about the time it takes to reply, I understand people get busy and I greatly appreciate you taking the time to give a thorough response. I had a bit of extra time to tackle this over the weekend. Something like slack or discord would be great! I have used discord but I understand slack is virtually the same thing- I have added my discord info on my profile but if you want to set something up on slack just let me know. 

I will play around with the information and see what I can do. I already have some smaller questions building up, but I'll save them for now. 

I agree on what you say for Notebook-wide settings. I like the idea that if I want to embed a notebook within an iframe onto an otherwise *simple* HTML page, depending on the user privilege or view, certain users may get full-access to edit the notebook and that the ultimate end user cannot circumvent this config.

**Comment by unhott** [comment]
With your feedback and some digging I was able to hack together a somewhat working cell lock feature ( https://github.com/unhott/starboard-notebook/commit/fdbf021702ee508b79535e9e6b6d33c3a7ac6242 ) I'm not extremely familiar with variable scoping, but I was having some issues with an 'isLocked' boolean originally declared within the create editor functions. 

The behavior I would see is, if you initialize an editor while the cell is locked, then you unlock it, the cell wouldn't actually unlock until you toggle lock/unlock an extra time. 

I was able to read the 'readOnly' option directly from the monaco module and get rid of declaring a boolean to track it separately. I don't know if there is a performance penalty for this vs a basic boolean flag. If I can figure out how to read the readOnly configuration of the cm editorView then the issue I am seeing should go away. 
Or I suppose if it was properly refactored by someone who knows what they're doing ;)

**Comment by gzuidhof** [comment]
I made some progress on this (as I needed this myself for a different project!), now there's a global "config" for a notebook under `runtime.config`, and also it's easier to inject more 'config' from the surrounding webpage.

If you're still up for chatting, I finally added you on Discord (my username is Kiet#0115, I couldn't add a message to the friend request)..

**Comment by gzuidhof** [comment]
I'm going to close this issue for now, although obviously this is a larger design discussion we can continue in separate threads.
There is now the `starboard-wrap` package which will help with getting up and running, and as the "initial content" you send an object instead of a string, allowing us to pass along "config" values.

**Comment by unhott** [comment]
Very awesome, I look forward to playing with and learning about these new features!
