### ISSUE TITLE
Why use a custom syntax instead of standard(-ish) markdown?

### ISSUE THREAD

**Issue by Sheraff** [gzuidhof/starboard-notebook#2]
After playing around w/ your codebase, I found that it's not very complicated to convert the parser to use the standard code block marks (<code>```</code>) instead of a custom `%%`.
All text outside of a code block is considered markdown, and (even though I haven't had a use for it yet) front matter could be its own code block syntax.
<pre>
``` frontmatter
title: this notes' title
```
# Here's my example

I'm writing markdown
- it's default syntax so it's more universal
- it's about as easy to parse

``` js autoRun
// even though not strictly correct, adding properties after the syntax type doesn't break most parsers
```
</pre>

So what am I not seeing?

**Comment by gzuidhof** [comment]
I considered this at the start, I think it's how [rMarkdown](https://rmarkdown.rstudio.com/) does it. These are the reasons I decided against it:

* It makes the editor quite a bit more complicated: if you create a new ``` block would a new cell be created? What if this happens in the middle of an existing cell, should we split the cell, what happens to the output?
* If the editor in the end is one big text file (that's how [Project Iodide](https://alpha.iodide.io/) does it), we'll have to make the editor syntax highlight and autocomplete correctly within a single text file. 
* The properties would indeed be a bit of an issue, I think in the future these may grow quite a bit and a block becomes more sensible, maybe with triple percentage sign, something like this with TOML? 
```
%%% js
runOnload: true
hideOnLoad: true
id: my-custom-id-to-refer-to-it-in-metaprogramming
%%%
```
* \``` is actually valid code in a lot languages and used for multi-line strings (like Go).
* It removes the ability to put code in markdown that is just illustrative, or text you just want monospaced.
* %% (in a comment or not) is how Project Iodide and [JupyText](https://github.com/mwouts/jupytext) does it and has some editor support (VS Code, Spyder).
* If you auto-generate the notebook text file and embed the data you want to plot into it (say 1MB of JSON blob), you probably don't want to show this.

All of the above are solvable problems, but at the cost of more complexity that I think outweighs the benefit.

Maybe instead there can be an "export as .md file" script? That could be a button on Starboard.gg, or you would use something like this from within a notebook:
```javascript
const { toMarkdown } = await import ("https://example.com/starboard-nb-to-markdown/index.js");
const mdString = toMarkdown(runtime.content.asString());

html`<button @click=${downloadAsFile(mdString)}>Export as Markdown</button>`
```
This `runtime` variable doesn't exist yet to do the metaprogramming, but something like that should be there so you can programmatically do things like add cells, run cells, get the text content of cells, etc.

**Comment by gzuidhof** [comment]
One more reason: I think Markdown is great but there's definitely alternatives out there like [AsciiDoc](https://asciidoctor.org/docs/what-is-asciidoc/) that are worth supporting too.

**Comment by Sheraff** [comment]
Thank you for this detailed answer. I'll keep playing around with your code and "standard" markdown, but now I know what to look out for ;)

In case you're interested: I'm trying to make a fully github-hosted version of this https://github.com/Sheraff/notebooks

**Comment by gzuidhof** [comment]
Cool! Let me know if there is something that is unclear or I can help with.

As for different notebook formats: I suppose there is no problem with having a parser for other formats if it's only a couple hundred lines. 

One proposal: it may mak more sense for your repo to use the starboard-notebook NPM package as a library instead of as a fork? Then we can share any improvements and not diverge. If you want to cherry-pick files intead of the whole bundle, you can find them in the [**dist/src folder**](https://cdn.jsdelivr.net/npm/starboard-notebook@0.2.2/dist/).

---
The minimal example page for a notebook is something like this:
```html
<head>
<script src="..../starboard-notebook.js"></script>
</head>
<body>

<script>
window.initialNotebookContent = `
%% js
console.log("Hello world!");
`
</script>

<starboard-notebook></starboard-notebook>
`
</body>
```

The transpile step to go from markdown-only format to %%-format could happen in that small script.
