### ISSUE TITLE
(minor) Menu to change cell gets cut off when the iframe is too small

### ISSUE THREAD

**Issue by unhott** [gzuidhof/starboard-notebook#26]
Behavior can be seen by adding a new cell at bottom and selecting menu to change cell type or properties.

Workaround is to add extra newlines to cell or to add many extra cells to be able to make the notebook large enough to see. 
Perhaps if the iframe size is too small, call iframe resize to make the iframe large enough to display the menu?

**Comment by gzuidhof** [comment]
Ah yeah.. I was able to fix it in a hacky way for the cell type selector (when you press the +) by forcing the notebook element to be at least large enough to fit that.. These solutions are really hacky but I guess we can do the same for those menus.

**Comment by gzuidhof** [comment]
https://github.com/gzuidhof/starboard-notebook/blob/master/src/components/cellTypePicker.ts#L50-L61

It really is quite terrible.

**Comment by gzuidhof** [comment]
Solved - at least for now, should be in next release :)
