### ISSUE TITLE
Troubles building the project

### ISSUE THREAD

**Issue by stefnotch** [gzuidhof/starboard-notebook#28]
I tried building the project in an attempt to hack in the [mathlive](https://mathlive.io/) editor.

However, while doing so, I ran into a fair number of issues and am still not sure if I got it to compile properly. This is what it looks like on my side:

![image](https://user-images.githubusercontent.com/10220080/116711990-ad8fad00-a9d3-11eb-8819-885c321740a1.png)

The issues I ran into were the following: 

1. The `minify-lit-html-loader` caused a ton of issues, so I ended up having to remove it.

```
PS C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-notebook> npm i
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\Stefnotch\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --cache=C:\Users\Stefnotch\AppData\Local\npm-cache\_cacache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! > minify-lit-html-loader@0.0.3 prepublish
npm ERR! > yarn run clean && yarn run build
npm ERR! npm WARN deprecated fsevents@1.2.4: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm ERR! npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
y-js` as of v3.13.0
npm ERR! npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm ERR! npm WARN deprecated core-js@2.5.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even i a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! 'yarn' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
npm ERR! npm notice
npm ERR! npm notice New minor version of npm available! 7.0.15 -> 7.11.2
npm ERR! npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.11.2>
npm ERR! npm notice Run `npm install -g npm@7.11.2` to update!
npm ERR! npm notice
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\Stefnotch\AppData\Local\npm-cache\_cacache\tmp\git-clone-b17f82b8
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c yarn run clean && yarn run build
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\Stefnotch\AppData\Local\npm-cache\_cacache\_logs\2021-04-30T13_58_14_869Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stefnotch\AppData\Local\npm-cache\_logs\2021-04-30T13_58_23_042Z-debug.log
PS C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-notebook> npm i

up to date, audited 1951 packages in 4s

found 0 vulnerabilities
PS C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-notebook> 
```

2. `node-sass` depends on `node-gyp`, which wants me to have Python installed. After some quick google-fu, it turns out that `node-sass` is deprecated in favour of `sass`.

```
PS C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-notebook> npm i
npm ERR! code 1
npm ERR! path C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-notebook\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.0.0 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-notebook\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-notebook\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-notebook\node_modules\graceful-fs\polyfills.js:295:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:194:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Stefnotch\\Documents\\GitHub\\Tools\\starboard-notebook\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Stefnotch\Documents\GitHub\Tools\starboard-notebook\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.0.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stefnotch\AppData\Local\npm-cache\_logs\2021-04-30T14_04_23_933Z-debug.log
```

3. Replacing `node-sass` with `sass` doesn't work, because `sass` wants Webpack 5. So I had to update to Webpack 5 and upgrade nearly all dependencies...which I suppose should be done anyways.

4. Here are [the changes I made on my side](https://github.com/gzuidhof/starboard-notebook/compare/master...stefnotch:testing-123). I probably missed a fair number of things that should be done. Also, is there a recommended code formatting style? I'm currently using Prettier, which tends to be rather aggressive. 

5. Upon opening the website, it took me way too long to find the teensy tiny "add cell" icon

**Comment by gzuidhof** [comment]
Hey @stefnotch 

Sorry for the trouble you had to go through :(. 

> The minify-lit-html-loader caused a ton of issues, so I ended up having to remove it.  

Yeah it's really quite terrible. A lot of the craziness in the webpack config is to work around it's outdated ES support. I suppose that dropping it entirely for now makes sense (although it does decrease the bundle size quite a bit!).


> 2 & 3  

The reason I wasn't able to upgrade to Webpack 5 yet was the Monaco editor's [ridiculously fragile webpack plugin](https://github.com/microsoft/monaco-editor-webpack-plugin). Maybe by now they support Webpack 5.. I'm seriously considering dropping the Monaco editor entirely, we could then use `esbuild` and build within a second instead of half a minute..

> Also, is there a recommended code formatting style? I'm currently using Prettier, which tends to be rather aggressive. 
 
There isn't, I should throw everything through prettier. I've been using Deno for code formatting (it's more similar to `go fmt` and written in Rust), I'll work on making that a bit more accessible and fleshed out.

> Upon opening the website, it took me way too long to find the teensy tiny "add cell" icon  

A good fix would be a placeholder with a some text that says "This notebook has no cells, click to insert first cell".. TODO
 
---
I would urge you to make changes to starboard-notebook itself, and make it a plugin instead. It will make your development cycle much faster. You can use [`starboard-cli`](https://github.com/gzuidhof/starboard-cli) to open a local notebook file, but if you have starboard-notebook itself working locally then that may make any debugging easier.

You would create a separate repository with its own build pipeline (use esbuild, rollup, or whichever is your favorite tool), and load the bundle into a notebook with a (dynamic) import statement. In your index file you would put [something like this](https://github.com/gzuidhof/starboard-python/blob/master/src/index.ts#L121-L137).

In your output folder, you could then run
```
http-server --cors --port 8080
```

Then you would create a notebook with the following in a ESM cell that runs when you load the notebook:
```javascript
import {plugin} from "http://localhost:8080/my-bundle-name.js";
runtime.controls.registerPlugin(plugin, {optional: "object-with-config"})
```

or in raw nb file:
```
# %%--- [esm]
# properties:
#   run_on_load: true
# ---%%
import {plugin} from "http://localhost:8080/my-bundle-name.js";
runtime.controls.registerPlugin(plugin, {optional: "object-with-config"})
```
If you want, perhaps you can add me on Discord (`Kiet#0115`). It's all a bit esoteric at the moment :(.

Finally - if you only want to integrate mathlive as part of the text editor, maybe instead [Prosemirror Math](https://github.com/benrbray/prosemirror-math/) is the right place for this functionality, that's the package that is used for inline LaTeX editing.

**Comment by gzuidhof** [comment]
On Starboard-cli - it looks like the latest version has some issues opening notebooks rendering that option not viable until I fix that :(

**Comment by stefnotch** [comment]
> Hey @stefnotch
> 
> Sorry for the trouble you had to go through :(.

Thanks for the super quick and detailed response! Don't worry about the troubles, I pretty much just reported them so that the next poor soul won't have the same issues :)


> 
> > The minify-lit-html-loader caused a ton of issues, so I ended up having to remove it.
> 
> Yeah it's really quite terrible. A lot of the craziness in the webpack config is to work around it's outdated ES support. I suppose that dropping it entirely for now makes sense (although it does decrease the bundle size quite a bit!).
> 

I wonder how hard it would be to write a better `minify-lit-html-loader`


> > 2 & 3
> 
> The reason I wasn't able to upgrade to Webpack 5 yet was the Monaco editor's [ridiculously fragile webpack plugin](https://github.com/microsoft/monaco-editor-webpack-plugin). Maybe by now they support Webpack 5.. I'm seriously considering dropping the Monaco editor entirely, we could then use `esbuild` and build within a second instead of half a minute..
> 

Yes, super please do upgrade to Webpack 5 and esbuild!
If Monoaco is causing any issues, please do comment it out, upgrade to a newer toolchain and then I'll try to get it to get Monaco to work again. I've got a bit of experience with it by now, since I had to go through the same fun myself. [Last time I tried it out](https://github.com/tuwien2020/tgi-pages/search?q=monaco-editor), I ended up using [monaco-loader](https://github.com/suren-atoyan/monaco-loader).


> > Also, is there a recommended code formatting style? I'm currently using Prettier, which tends to be rather aggressive.
> 
> There isn't, I should throw everything through some formatter. I've been using Deno for code formatting (it's more similar to `go fmt` and written in Rust), I'll work on making that a bit more accessible and fleshed out.
> 

Sounds great!


> > Upon opening the website, it took me way too long to find the teensy tiny "add cell" icon
> 
> A good fix would be a placeholder with a some text that says "This notebook has no cells, click to insert first cell".. TODO
> 

Fully agree, that would be a nice fix indeed


> I would urge you to avoid make changes to starboard-notebook itself, and make it a plugin instead. It will make your development cycle much faster. You can use [`starboard-cli`](https://github.com/gzuidhof/starboard-cli) to open a local notebook file, but if you have starboard-notebook itself working locally then that may make any debugging easier.
> [...]

Thank you for the suggestion! I'll try it out :)


> If you want, perhaps you can add me on Discord (`Kiet#0115`). It's all a bit esoteric at the moment :(.
> 

Sure thing!


> Finally - if you only want to integrate mathlive as part of the text editor, maybe instead [Prosemirror Math](https://github.com/benrbray/prosemirror-math/) is the right place for this functionality, that's the package that is used for inline LaTeX editing.

That's a great suggestion! I'll explore this avenue :)

**Comment by stefnotch** [comment]
Sweet, with the latest version of Starboard, it compiles without any major issues! I'll close this issue then.
