### ISSUE TITLE
npm install with "premature close" error

### ISSUE THREAD

**Issue by llagerlof** [gzuidhof/starboard-notebook#3]
```
Windows 8.1 64
npm 6.14.4
```

I cloned the repository and executed the `npm install`.

npm does his magic but at some point during installation I received the following error:

``` 
16269 error premature close   
16270 verbose exit [ 1, true ]
```

**Comment by llagerlof** [comment]
I tried more than once. Same error.

**Comment by gzuidhof** [comment]
I think this is most likely an issue installing one of the dependencies, this project doesn't have any special steps when installing. My first suspect would be one of the native packages in the dev dependencies.

Maybe the best first step would be to try to narrow it down to the package causing the problems. You  could do this by manually npm installing the dependencies in package.json one by one.

**Comment by llagerlof** [comment]
Found the guilty package.

I tested one by one. The only package returning this problem on install is the `minify-lit-html-loader`.

I tried:

```
npm i minify-lit-html-loader@github:mantou132/minify-lit-html-loader
```

and

```
npm i minify-lit-html-loader@0.0.3
```

Same problem:

```
npm ERR! premature close                                              
```

**Comment by gzuidhof** [comment]
I'm afraid I still don't have any next steps to help out here :(. I have tried installing on Windows, Mac and Linux (Ubuntu) without issues. I expect it may be one of the dependencies of minify-lit-html-loader. Maybe there is a verbose mode for npm you can try?

**Comment by llagerlof** [comment]
Well, I tried `npm install` using an elevated cmd, and that package was installed without issues. For me, you can close this issue. Thank you for your help.

**Comment by gzuidhof** [comment]
Great, if it happens in the future to somebody else too I'll add it to a troubleshooting section.
