### ISSUE TITLE
Add a Copyfree License

### ISSUE THREAD

**Issue by sirinath** [gzuidhof/starboard-notebook#35]
I am wondering if you can add a [copyfree](https://copyfree.org/) license also along with MPL.

**Comment by stefnotch** [comment]
I found that site to be somewhat confusing. What's the point of a copyfree license/why would it make sense?

For example
> Free Modification and Derivation
> A copyfree license does not place any restrictions on the modification of -- and derivation from -- the licensed material external to the license itself, and protects recipients of the material from such restrictions except insofar as explicit individual contractual agreements may be concerned.
> -- <https://copyfree.org/standard>

That sounds really nice, until you realize that recipients includes companies. Which means that with a copyfree license, any company can take the entire piece of software and sell it. They don't even have to give any credit to the original author...

**Comment by gzuidhof** [comment]
Hi sirinath,

@stefnotch summed it up pretty well - the current license is not very restrictive (only changes to the actual starboard-notebook files should be open sourced), and with the plugin system it is actually unlikely you will even need to do that regardless of your usecase or integration. I think that restriction is fair, if some commercial party wants to keep the changes of their internal fork private then we can work out some sort of other license in return for a monthly sponsorship amount.
