### ISSUE TITLE
wasm out of memory when page is refreshed several times

### ISSUE THREAD

**Issue by RossSmyth** [gzuidhof/starboard-notebook#37]
Hello,
I have noticed that if the page is refreshed several times (to reset my workspace), web assembly runs out of memory and is not able to load Pyodide. I think part of this is that I load a 5 MB dataset to the notebook via JavaScript, then copy it to Python. I can improve that on my side, but also clearing selectively clearing the cache on reload so the the Pyodide executable isn't lost would improve this. I'm not very familiar with this so I'm not much help without some research.

Thanks!

**Comment by RossSmyth** [comment]
Here is a memory snapshot I took. It seems to mostly be the data I loaded.
![firefox_OLjCjlujEU](https://user-images.githubusercontent.com/18294397/119168322-c87f9b00-ba2e-11eb-946a-f9610d41a4f7.png)

**Comment by gzuidhof** [comment]
Hi Ross,

From what I remember reading somewhere in Pyodide's issues (https://github.com/pyodide/pyodide/issues/1513#issuecomment-824221403), this is a Firefox issue where reloading the page doesn't lead to all the memory gets cleared (especially for WASM "stuff"). For that reason I don't think there's something we can do on the Starboard side (except for maybe hacking around it by chagning the URL every time whenever refreshed with `?r=<random string>`, haven't tried that though). I run into this myself every now and then too when developing :(.

I generally switch to Chrome (reluctantly) during fast iteration when developing a notebook that uses Pyodide

**Comment by RossSmyth** [comment]
Ah ok, I'll close this since it's upstream then.
