### ISSUE TITLE
Matplotlib only allowed once

### ISSUE THREAD

**Issue by patrickmineault** [gzuidhof/starboard-notebook#41]
When I try to show two matplotlib plots in a page with python kernels, they clash with one another, and a second call draws into the original plot, not in the old plot as expected.

https://starboard.gg/nb/n4z44Wh

**Comment by unhott** [comment]
Hi @patrickmineault , if I add fig = plt.figure() at the top of the second python cell it shows 2 figures for me.

**Comment by patrickmineault** [comment]
I will close this as a quirk rather than a genuine bug.

**Comment by unhott** [comment]
Yeah, I think there is a LOT of 'magic' with matplotlib, intended to make it easier to use. 

I suspect that this quirky behavior is due to upstream pyodide decisions or issues related to how these types of 'magic' behave.
