### ISSUE TITLE
require not supported

### ISSUE THREAD

**Issue by patrickmineault** [gzuidhof/starboard-notebook#42]
Some libraries, in particular mathjs, can be imported via `require` but not via `import` ([example usage](https://mathjs.org/examples/browser/requirejs_loading.html.html)). Unfortunately, `require` is not built in. I've tried to load `require` via import, but that doesn't work. I've also tried to load it via a `<script src` in an HTML cell, also fails. I've resorted to copying and pasting the entire source of requirejs into a cell so I can then require mathjs - inelegant but it does work. Can we have easier access to `require`?

**Comment by unhott** [comment]
Hi Patrick,
I personally don't know much about this sort of thing, so I can't really speak about require. I'm sure @gzuidhof will write a detailed response when he gets a chance :)  

In the meantime, try this as an ESM cell. 

import * as mathjs from 'https://cdn.skypack.dev/mathjs@8.0.1';
console.log(mathjs.add(1,2));

See if you can work up to what you need from there, hopefully this helps!

**Comment by gzuidhof** [comment]
Hi Patrick,

You're right that requrie is not built in, require is really a Node.js thing (for an import system called CommonJS), whereas the browser is using something called ES Modules. I like to stick close to the browser (and Node is also moving to ES Modules slowly!).

There are a few CDNs which will transpile requirejs packages into ES Modules, such as [skypack](https://www.skypack.dev/) (see the comment above, thank you @unhott), and [JSPM](https://jspm.org/), I think using those will be the best solution.

**Comment by unhott** [comment]
Interesting! I didn't realize that skypack was a thing. I just browsed codepen for ones using mathjs and tweaked it slightly to see if it would work here, and it appeared to :)

**Comment by patrickmineault** [comment]
Awesome! Would be great if you had a series of tutorials or documentation
for noobs regarding this - this is the kind of thing you can easily spend
an afternoon figuring out.
