### ISSUE TITLE
Webcam access (starboard.gg hosting)

### ISSUE THREAD

**Issue by boisgera** [gzuidhof/starboard-notebook#56]
Hi Guido,

Any idea why `getUserMedia` wouldn't work out of the box in the context of starboard.gg hosting?

I end up with a `NotAllowedError` for https://starboard.gg/nb/nI3Psrm while the same notebook hosted on github pages (https://boisgera.github.io/webcam/starboard.html) works as expected (I am asked for permissions and once granted, I get the stream).

I have the same behavior with Firefox and Chrome (Linux). As far I can tell (but I may be wrong) I have no specific setting in these browsers that would deny automatically the access to the webcam from the starboard.gg domain.

Cheers,

SB

**Comment by gzuidhof** [comment]
It looks like there's [a feature policy that needs to be set on the iframe](https://blog.addpipe.com/camera-and-microphone-access-in-cross-oirigin-iframes-with-feature-policy/) which Starboard.gg doesn't do (yet). Firefox support seems a [bit iffy](https://caniuse.com/feature-policy), but I'm happy to add an allow tag to starboard.gg which should fix this issue.

**Comment by gzuidhof** [comment]
You can try again now :)

**Comment by boisgera** [comment]
Works like a charm, thank you ! :+1:
