### ISSUE TITLE
Building the application on Windows fails when tries to delete the dist directory

### ISSUE THREAD

**Issue by llagerlof** [gzuidhof/starboard-notebook#6]
On Windows `npm run build` throw an error because Windows doesn't have the `rm` command natively.

However, I've managed to build the application running the commands separately, without the `rm` (I deleted the `dist` directory manually):

```
npm run build:notebook
tsc
```

**Comment by gzuidhof** [comment]
I changed it to use [rimraf](https://www.npmjs.com/package/rimraf) instead, that should work in Windows too!
Let me know if it works for you.

**Comment by llagerlof** [comment]
`npm run build` working flawlessly. Thank you.
