### ISSUE TITLE
SQL Cell?

### ISSUE THREAD

**Issue by twoxfh** [gzuidhof/starboard-notebook#72]
I do not see a discussions tab, but wanted to understand any thoughts towards a SQL Cell? I am still working towards understanding the plugin system, however, I did create a sample notebook using starboard-editor and wa-sqlite [here](https://twoxfh.github.io/starboard-editor/?notebook=bw1%40G5oIAByFcZvThDY8qARN7PbNQN0aJob9XpOgnnff0NbzVQFKwUiHK4Wa8HU30eUIhG9.-ZraJAVScSVyZ1xZyty.3X8BBlcg0p0aG6EK7F2P8DYqHfZQ.danJzg7w0KLnFXFu5RvQyhl4NgWdDwx6Hhh0BOLWvU3L6sfOAx.LyMbULHT0hvA2k6sf7PCbUWZF6z6oSDcpJdHN7y9u-Qu1grnL.5Z6Os.C9NVpnCy-seJmUuTovKj36KjmyrgWU91InwqBurJFHo1WTnJeWKYUA81nFNZsJ2shreZA6a5NdsJVt-usBacTGGkMdpWz5ODhZ1WWKGUoXeOvby3LqOj6LhzVjosuoBUN0dQ9tZGaxhma3Nu2pdMwxw80wRH9Ey..tJDkh7r5Rm9Dm7Z0ELJbhrP1AYqJmdaG9zOfAb5jA837BEFuU5unUjMIh4WWr5Gli5hTUfyKX1ZalMw8It0GTnpAwKcc7RZ6pAAFbqz-nbm98HNTBj2.2R9WivXe7CvWRVcGtF0BmIRAa1nGJthsDMLxBqmunE1oDYNLX6.HcnX7glDrV1LfgQ1UCg824.6LDpM2iIt1vQl1bdqj3bvIfbQQIWdvCTknoOnDF5W3fPnt2m7SCu6ZJiMMcqN7sNZ1kNJobpqWiyNIK8R0Yf0QaFGGC4RxhQN0AjacOY0.8ZeHfVk8yD-kZOwktTx7uBd9SqAA.AJP5ATlAd-v99ErN3-vj.XkKJUN8iX1f09zrxcN5uGiM1EbgqvFcjAe3U3-Pg-W6qI4lYmNaLAFrHWCHyaTec-IooxWFWqkCJ.l8ulGoVKi0PaF81OOtfuI.zxlFd.9tfjH5io2MStLZrCMwicImmtwifISJtdm9FwKrQNDimThC57acEFqy7TOxzY22yY1CkIMVUmLbhOhHF7N2n3.zjF3Y09pS3W06A5wHRvaLeoKtdJ.A9lBUndezhdQz0UP3APCuySt261DE8D505jJ78PgbiEsZXSs-zXZSGX03XP8fH599.BRTgMecIc26cjs20dNPQylic8Og9eYFls2p4BybsDp3OBVaKH7qo1IeZI6dx-wPPs5vwz4hx6TRAnKCgFsUOnUWyRcwY_&c=true&name=sqlite.md.txt)

**Comment by unhott** [comment]
I think it's a great idea. 

Check out this example for defining a custom cell type within the notebook itself: https://starboard.gg/gz/coffeescript-custom-cell-type-n1VJRGC

gzuidhof made this to demonstrate creating a custom cell type. I think you could simply tweak this for SQL. You just have to define what it means to run the cell and what to render to the output. 

Once you have that core design in place, it shouldn't be difficult to convert to a plugin :D

**Comment by gzuidhof** [comment]
I enabled the Discussions tab now :)

I think a SQL-powered celltype would be cool! But (there's always a but) I think it's better as a plugin, in a plugin you still have pretty much complete freedom just as much as if it was integrated into the standard Starboard bundle (yay modern browsers!).

Happy to help out and give pointers of course :)

**Comment by twoxfh** [comment]
Here is an updated version using the custom cell type [sql example](https://twoxfh.github.io/starboard-editor/?notebook=bw1%40GyMLAIzTDfclJvHM-9TprmV6-SU5J8sFtE8FgCloaqqQSUGfAsQv9zZjkViMRqu-edlcaUXSW-bnrqNqE7Z0x6CwktdodR1PKKAsV27M-7aOzc1mWo3bTJ8-oYGwwvfnizZNCQ1tD6bp32aeLf7.ZV.b-2kkdeapVzGOuNJNelUZJ4sRedsNc12TmDW4Vm.-X1vo6i3-PYmujDcP3TSUSdNyvJ9icTapmIy.6RS.3S.DQjmdSBqVA6HITSS6SKIBN91cFVp50h6g47WTho9U.PkbZfwOzDSm-UZxZPlIhaHuYDSHukOWPNCd2iMrFWoGYGR1koSbJvFHYkWjobOrSVUxojYIZUS3xlXyOWpM5GirA3WGSTrHEvUgeL3SBH6bGcEsYwXavS.jZmkaxzUyY6Iz3wYAX0UYaajDiAAKKltzwInYVGr91Kgsxhmb1IkKdZ61ZW5o7Hu2UaQRabeORN1.p0CHZq5duIfNwx9b0qNUZD88Hl.fNFejyHlMNif6UTrWhtc68WVeIXUijKXa9PX7ZuYLZJ0UBqw64MPcZarKa3iwut.U.nEb1tGWX9siEe6h-W3AsUNaAcv666hArxdMllcMST8gwRZhZaTN-y2HIpBGGyOYMIJmRuG7zKyu3iitjpoc5yoeFtaoidrvpf16kbfOwhZM.kg7VT.FkhOiIiYLHj8x.sILsGcohPNQu8IoZwwC.LfqPhRuTG7ASeLnk4ixJqVhu9jene3x7fHy5irs0YPd.U.jrM-JpJUhgFUYyyZdWIaVjuNQ5tWgdbeDHOTKdNqe4olrehs13yNtrxCgiyzt7yfq99NFGvMkEhLsEbzM5iLgUnUSNhLCM8bIAEoMPIiKYOhlV0i9ZEx7nvzq68EhdsbbB9UaxC5L-pMtgspsTv6pCIu9Rx8iihC9.qegnLrbKEuqVwmy3CybhSMotIKMyKWl-5Y8YVvTukvf2uhC0UBX5obiI.JUX1PqGw0oq2LhtHRbhkkypQINhVwgDKn4NECB4wUmjWLUk5uzcNTG4Zpn-oaNdHWQy2DxezrnVDMRTPZVbISVM.eRdOPM85GW.WSjYiCqa8bz6CS9f1lWYZi3lmjMh1NTQZ32bQ63rWAmHHS4KDEqsodLqREMWmtvy50uu.Fujidi1YRlUT70cCI2qTgBCy8nqmKE.JhUrNLDdKpWU6RVf996jjMAf1n1eAM9MTZqv4SVeZU0YjYwLKtKvnd46IBvdqfLtX5x6NhQAzhiV2NOkMtIIzSFlSLdMDkUAA_&c=true&name=sqlite.md.txt) @unhott suggested

I made the result output JSON so it can easily work with charting, but open to other ideas. I am also wondering how we can integrate WASM file storage with a cell type @gzuidhof . I would like to upload CSV files and have SQLite do the crunching. 

Thanks!

**Comment by twoxfh** [comment]
@gzuidhof I have a SQL-JS [branch](https://github.com/twoxfh/sql.js/tree/es6module) which outputs an ES6 module which can be loaded. Will close this issue, thanks for the feedback!
