### ISSUE TITLE
Error!How to do?

### ISSUE THREAD

**Issue by AndersonHJB** [gzuidhof/starboard-notebook#77]
Microsoft Windows [版本 10.0.19043.1288]

clela@AIYC C:\Users\clela\Downloads\starboard-notebook-0.14.2
# npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
added 620 packages from 313 contributors and audited 620 packages in 14.579s
found 7 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

clela@AIYC C:\Users\clela\Downloads\starboard-notebook-0.14.2
# npm run build

> starboard-monorepo@0.0.1 build C:\Users\clela\Downloads\starboard-notebook-0.14.2
> lerna run build

lerna notice cli v4.0.0
lerna info Executing command in 3 packages: "npm run build"
lerna ERR! npm run build exited 1 in 'starboard-rich-editor'
lerna ERR! npm run build stdout:

> starboard-rich-editor@0.14.2 build C:\Users\clela\Downloads\starboard-notebook-0.14.2\packages\starboard-rich-editor
> tsc -b

lerna ERR! npm run build stderr:
'tsc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! starboard-rich-editor@0.14.2 build: `tsc -b`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the starboard-rich-editor@0.14.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\clela\AppData\Roaming\npm-cache\_logs\2021-11-10T03_34_55_249Z-debug.log
lerna ERR! npm run build exited 1 in 'starboard-rich-editor'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! starboard-monorepo@0.0.1 build: `lerna run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the starboard-monorepo@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\clela\AppData\Roaming\npm-cache\_logs\2021-11-10T03_34_55_325Z-debug.log

clela@AIYC C:\Users\clela\Downloads\starboard-notebook-0.14.2
#

**Comment by AndersonHJB** [comment]
help me!

**Comment by gzuidhof** [comment]
Hi Anderson,

I am sorry you are running into some issues. Building the project is a bit undocumented (I need to get a clean machine and document the steps - but other work has been getting into the way). Saying "please" does go a long way...

Here are the steps I would try:
* Update your Node & NPM, it looks like it's quite outdated as it's mentioning only supporting lockfile version 1.
* Please don't upgrade to Node 17 yet, so stick to 16. It has issues with some rollup plugins.
* 
```shell
# from the root
npm install
npm run lerna bootstrap
npm run build
```
* Then you can CD into the package you want to work on and stuff will hopefully work.
* Another issue actually seems to be the typescript compiler not being happy, but the encoding looks all messed up. You will have to investigate this first, perhaps it's trying to display an error message in Mandarin?
```
'tsc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

----
It looks like there was an issue with lerna not understanding the build order when building from scratch, I have now committed a fix for this.
