### ISSUE TITLE
Insert Cell and Remove Cell broken in latest release

### ISSUE THREAD

**Issue by travisennis** [gzuidhof/starboard-notebook#9]
I noticed that with release 0.4.0 that insertCell and removeCell throw errors:

`TypeError: undefined is not an object (evaluating 'this.insertCell')`

and 

`TypeError: undefined is not an object (evaluating 'this.removeCell')`

Insert cell does seem to work if you are inserting a cell at the bottom of the notebook. 

These errors still exist in the 0.4.1 release as well.

**Comment by gzuidhof** [comment]
Oh no :( Thank you for letting me know, I will revert to 0.3.2 for starboard.gg and investigate!

**Comment by gzuidhof** [comment]
Found the issue, somehow this slipped in:
```export function createRuntime(this: any, notebook: StarboardNotebookElement): Runtime {```

That `this` definitely shouldn't be there, I changed the whole function to not rely on `this`.

I made a new release on NPM and after some initial tests it looks fine now.

To force a version on Starboard.gg you can use add `?runtime=0.4.2` (e.g. https://starboard.gg?runtime=0.4.2). I will make 0.4.2 the default version tomorrow morning to minimize risk of something else being broken overnight

**Comment by travisennis** [comment]
Looks like 0.4.2 did fix the issue with insert and remove cell. I'll keep playing around with it to see if there are any other issues, but it looks like the specific issue has been addressed.

**Comment by gzuidhof** [comment]
Thank you again! I will close this issue tomorrow when I make 0.4.2 the default on Starboard.gg.

I really need to invest some time into more end to end testing..
